// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://pwsljblxtguugzganobi.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InB3c2xqYmx4dGd1dWd6Z2Fub2JpIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQ1MjQzNDgsImV4cCI6MjA2MDEwMDM0OH0.X118e1yXocoNb_WChi5ZRdUruPlgKzsPaij6MIzHE2Q";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);